title: "Anusha Parida – Analyst & Software Engineer"
email: "work.anushaparida26@gmail.com"
description: "Portfolio of Anusha Parida – Data Analyst | Business Analyst | Software Engineer"
baseurl: "" 
url: "https://Anusha26399.github.io"
theme: minima
github_username: "Anusha26399"
linkedin_username: "anusha-parida-94ab84273"
